import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between p-4 bg-gray-800 text-white">
          <div className="text-lg font-bold">Crypto Dashboard</div>
          <div className="flex space-x-4">
            <Link href="/" className="hover:underline">
              Home
            </Link>
            <Link href="/admin" className="hover:underline">
              Admin Panel
            </Link>
            <Link href="/auth" className="hover:underline">
              Auth Section
            </Link>
          </div>
        </nav>
        <main className="container mx-auto">

          {children}
        </main>
      </body>
    </html>
  );
}


export default RootLayout;